
name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/setup-gradle@v3

    - name: Build with Gradle
      run: gradle build

    - name: Extract version name
      id: version
      run: echo "VERSION_NAME=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\(.*\)\"/\1/p')" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.VERSION_NAME }}
        release_name: Release v${{ env.VERSION_NAME }}
        body: |
          Automated release for version ${{ env.VERSION_NAME }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
